spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/stackoverflow
#spring.datasource.username=${DB_USER:ADMIN}
#spring.datasource.password=${DB_PASS:ADMIN}
#spring.datasource.username=postgres
#spring.datasource.password=parolapostgres
spring.datasource.username=ADMIN
spring.datasource.password=ADMIN
spring.jpa.hibernate.ddl-auto=update
upload.dir=uploads
spring.web.resources.static-locations=file:uploads/

# Local non-Docker citeste secrete din ./secrets.properties; in Docker vin din .env.
spring.config.import=optional:file:./secrets.properties

notification.service.url=${NOTIFICATION_SERVICE_URL:http://localhost:8081}
