spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/stackoverflow
#spring.datasource.username=${DB_USER:ADMIN}
#spring.datasource.password=${DB_PASS:ADMIN}
#spring.datasource.username=postgres
#spring.datasource.password=parolapostgres
spring.datasource.username=ADMIN
spring.datasource.password=ADMIN
spring.jpa.hibernate.ddl-auto=update
google.drive.folder.id=1ejgyaXvmQRvbGHEqOtBKqJE7GlCJkmhv